ECOM/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("product.urls")),
    path('auth/',include('UserProfile.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

UserProfile/urls.py
from django.urls import path
from .import views
app_name="auth"
urlpatterns=[
    path('Signup',views.SignUpView,name="Signup"),
    path('Login',views.LoginView,name="Login"),
    path('Logout',views.LogoutView,name="Logout"),



]

product/urls.py
from django.urls import path
from .import views
app_name="product"
urlpatterns=[
    path('',views.ProductView,name="ProductList"), 
    path('category',views.CategoryView,name="Categorylist"),
    path('product/<slug:slug>',views.ProductDetailView,name="productDetails") ,
    path('addProduct',views.AddProductView,name="Addproductlist"),
    path('edit/product/<slug:slug>',views.EditProductView,name="editproductlist"),
    path('addCart',views.AddCartView,name="AddCartlist"),
    path('Cartlist',views.CartViewList,name="cartViewlist"),
    path('product/delete/<int:id>',views.DeleteProductView,name="deleteproduct"),
    path('checkout',views.CheckoutView,name="Checkout")

]

product/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=50)
    slug=models.SlugField(blank=True,max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    def save(self,*args,**kwargs):
        self.slug=slugify(self.name)
        return super(Category,self).save(*args,**kwargs)
    
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural="Categories"
class Tag(models.Model):
    name=models.CharField(max_length=50)
    slug=models.SlugField(blank=True,max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    def save(self,*args,**kwargs):
        self.slug=slugify(self.name)
        return super(Tag,self).save(*args,**kwargs)
    
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural="Tags"
class Product(models.Model):
    name=models.CharField(max_length=60)
    slug=models.CharField(blank=True,max_length=60)
    auth=models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE,null=True,blank=True,related_name="category")
    productImage=models.ImageField(upload_to="productImage",null=True,blank=True)
    tag=models.ManyToManyField(Tag,null=True,blank=True)
    desc=models.TextField()
    price=models.IntegerField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    def save(self,*args,**kwargs):
        self.slug=slugify(self.name)
        return super(Product,self).save(*args,**kwargs)
    
    def productimage(self):
        try:
            url=self.productImage.url
        except:
            url=''
        return url
    
    def __str__(self):
        return self.name
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    quantity=models.PositiveIntegerField(null=True,default=1)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.product.name
    def totalPrice(self):
        return self.product.price *self.quantity
class ShippingAddress(models.Model):
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Cart, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

    

    
    

product/forms.py
from django.forms import ModelForm
from .models import *
class ProductForm(ModelForm):
    class Meta:
        model=Product
        fields='__all__'
    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
class CheckoutForm(ModelForm):
    class Meta:
        model=ShippingAddress
        fields='__all__'
    def __init__(self, *args, **kwargs):
        super(CheckoutForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
class EditForm(ModelForm):
    class Meta:
        model=Product
        fields='__all__'
    def __init__(self, *args, **kwargs):
        super(EditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

product/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import *
from .forms import ProductForm
# Create your views here.
def ProductView(request):
    cat=request.GET.get('category')  if request.GET.get('category') != None else ''
    categories=Category.objects.all()
    products=Product.objects.filter(category__slug__icontains=cat)
    context={
            'products':products,
            'categories':categories
    }
    return render(request,"base/productlist.html",context)
    
def ProductDetailView(request,slug):
    product=get_object_or_404(Product,slug=slug)
    context={'product':product}
    return render(request,"base/productDetails.html",context)
def CategoryView(request):
    category=Category.objects.all()
    context={
        'categories':category
    }
    return render(request,"base/category.html",context)
def AddProductView(request):
    if request.method == "POST":
        form=ProductForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form=ProductForm()
    context={
        'form':form
    }
    return render(request,"base/addproduct.html",context)
def EditProductView(request,slug):
    instance=get_object_or_404(Product,slug=slug)
    if request.method == "POST":
        form=ProductForm(request.POST,request.FILES,instance=instance)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form=ProductForm(instance=instance)
    context={
        'form':form
    }
    return render(request,"base/editproduct.html",context)
def AddCartView(request):

    product_id=request.POST.get('product-id') if request.POST.get('product-id') !=None else ''
    product=get_object_or_404(Product,id=product_id)
    print(product)
    cartitem=Cart.objects.filter(product=product,user=request.user)
    for cart in cartitem:
        cart.quantity +=1
        cart.save()
        return redirect('product:cartViewlist')
    if not cartitem:
        cartitem=Cart.objects.create(product=product,user=request.user)
        cartitem.quantity=1
        cartitem.save()
        return redirect('product:cartViewlist')
  
def CartViewList(request):
    cartdata=Cart.objects.filter(user=request.user)
    totalitem=cartdata.count()
    totalprice=sum(item.product.price *item.quantity for item in cartdata)
    context={
        'cart':cartdata, 
        'productcost':totalprice,
        'totalitem':totalitem  
    }
    return render(request,"base/cart.html",context)
def CheckoutView(request):
    pass

def DeleteProductView(request,id):
    productDel=get_object_or_404(Cart,id=id)
    productDel.delete()

    return redirect('product:cartViewlist')

product/templates/base/addproduct.html
{% extends 'base/base.html' %}
{% block content %}
<div class="add-product">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Add product">
    </form>
</div>
{% endblock %}

product/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<header>
    <div class="container-fluid ">
        <div class="row">
            <div class="col-12 p-0">
                <nav class="navbar navbar-expand-lg NavbarMenu ">
                    <div class="container-fluid">
                      <a class="navbar-brand text-white">ECOM</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            {% if request.user.is_authenticated %}
                            <li class="nav-item ">
                                <a class="nav-link active" aria-current="page" href="{% url 'product:ProductList' %}">Home</a>
                              </li>
                          <div class="right-item">
                            <li class="nav-item">
                              <a class="nav-link active " aria-current="page" href="">My Account</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link active " aria-current="page" href="{% url 'product:Addproductlist' %}">Add product</a>
                            </li>
                          <li class="nav-item">
                            <a class="nav-link active " aria-current="page" href="{% url 'auth:Logout' %}">Logout</a>
                          </li>
                          </div>
                          {% else %}
                          <div class="right-item">
                          <li class="nav-item  ">
                            <a class="nav-link active  " aria-current="page" href="{% url 'auth:Signup' %}">Signup</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link active " aria-current="page" href="{% url 'auth:Login' %}">Login</a>
                          </li>
                          </div>
                          {% endif %}
                          </ul>
                      </div>
                    </div>
                  </nav>
            </div>
        </div>
    </div>
</header>

<section>
    <div class="container">
        <div class="row">
            <div class="col-12 my-2">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</section>
<link href="{% static 'css/style.css' %}" rel="stylesheet" >
<link href="{% static 'bootstrap/bootstrap.min.css' %}" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</body>
</html>

product/templates/base/cart.html
{% extends 'base/base.html' %}
{% block content %}
<div class="row">
  <div class="col-9 mt-3">


<div class="add cart">
  
  {% if cart %}
  
    <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th scope="col">S.no</th>
            <th scope="col">product Image</th>
            <th scope="col">Name</th>
            <th scope="col">price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
            {% for cart in cart %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><img src="{{cart.product.productimage}}" width="50px" height="50px"></td>
            <td>{{cart.product.name}}</td>
            <td>${{cart.product.price}}</td>
            <td>{{cart.quantity}}</td>
            <td>${{cart.totalPrice}}</td>
            <td><a href="{% url 'product:deleteproduct' cart.id %}"><i class="bi bi-trash3"></i></a></td>
          </tr>
       {% endfor %}
        </tbody>
      </table>
      {% else %}
      <h2>No product Item</h2>
      {% endif %}
</div>
</div>
<div class="col-3">
  <div class="cartsummary" style="margin-top: 15px;">
  <h5 class="text-danger">Cart Summary</h5>
  <p>Sub Total :<span>${{productcost}}</span></p>
  <p>Shipping Cost :<span>$1</span></p>
  <hr>
  <p>Grand Total :<span>${{productcost|add:1}}</span></p>
</div>
<div class="checkoutContainer ">

  <button class="checkout my-2 btn btn-secondary">Checkout</button>
</div>
</div>

</div>
{% endblock %} 

product/templates/base/category.html
<div class="category">
    <h4> category</h4>
    <ul>
        <li>
            <a href="{% url 'product:ProductList' %}">All</a>
        </li>
        {% for category in categories %}
        <li>
    
            <a href="{% url 'product:ProductList' %}?category={{category.name}}">{{category.name}}</a>
        </li>
        {% endfor %}
         
    </ul>
    
    
    </div>

product/templates/base/editproduct.html
{% extends 'base/base.html' %}
{% block content %}
<div class="add-product">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="edit">
    </form>
</div>
{% endblock %}

product/templates/base/productDetails.html
{% extends 'base/base.html' %}
{% block content %}
<h3>{{product.name}}</h3>
<p>{{product.desc}}</p>
{% endblock %}

product/templates/base/productlist.html
{% extends 'base/base.html' %}
{% block content %}

<div class="row">
    <div class="col-3">
        {% include 'base/category.html' %}
    </div>
    {% for product in products %}
    <div class="col-3 ">
        <div class="product-item">
            
            <img src="{{product.productimage}}" id="prodcut-{{product.name}}">
         <div class="product-content">
            <h3 class="product-name">{{product.name}}</h3>
           </div>
            <div class="right-set">
            
              <h2 class="product-price">$<span>{{product.price}}</span></h2>
              <p>{{product.desc}} </p>
              <form method="post" action="{% url 'product:AddCartlist' %} ">
                {% csrf_token %}
                <input type="hidden" name="product-id" value="{{product.id}}">
                <button class="btn btn-primary">add To cart</button>
            </form>
              <a href="{% url 'product:editproductlist' slug=product.slug %}" class="text-white">Edit</a>
     
            </div>
        
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}